config/routes.rb
Rails.application.routes.draw do

	#Casein routes
	namespace :casein do
		resources :employees
		resources :brands
	end

  root "pages#index"
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_attached_file :image,
                    styles: { thumb: ["64x64#", :jpg],
                              original: ['500x500>', :jpg] }
                              validates_attachment :image, presence: true,
                              content_type: { content_type: ["image/jpeg", "image/gif", "image/png", "image/jpg"] }
end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/casein/brands_controller.rb
# Scaffolding generated by Casein v5.1.1.5

module Casein
  class BrandsController < Casein::CaseinController

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def index
      @casein_page_title = 'Brands'
  		@brands = Brand.order(sort_order(:name)).paginate :page => params[:page]
    end

    def show
      @casein_page_title = 'View brand'
      @brand = Brand.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new brand'
    	@brand = Brand.new
    end

    def create
      @brand = Brand.new brand_params

      if @brand.save
        flash[:notice] = 'Brand created'
        redirect_to casein_brands_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new brand'
        render :action => :new
      end
    end

    def update
      @casein_page_title = 'Update brand'

      @brand = Brand.find params[:id]

      if @brand.update_attributes brand_params
        flash[:notice] = 'Brand has been updated'
        redirect_to casein_brands_path
      else
        flash.now[:warning] = 'There were problems when trying to update this brand'
        render :action => :show
      end
    end

    def destroy
      @brand = Brand.find params[:id]

      @brand.destroy
      flash[:notice] = 'Brand has been deleted'
      redirect_to casein_brands_path
    end

    private

      def brand_params
        params.require(:brand).permit(:image, :name, :link)
      end

  end
end

app/controllers/casein/employees_controller.rb
# Scaffolding generated by Casein v5.1.1.5

module Casein
  class EmployeesController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Employees'
  		@employees = Employee.order(sort_order(:name)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View employee'
      @employee = Employee.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new employee'
    	@employee = Employee.new
    end

    def create
      @employee = Employee.new employee_params
    
      if @employee.save
        flash[:notice] = 'Employee created'
        redirect_to casein_employees_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new employee'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update employee'
      
      @employee = Employee.find params[:id]
    
      if @employee.update_attributes employee_params
        flash[:notice] = 'Employee has been updated'
        redirect_to casein_employees_path
      else
        flash.now[:warning] = 'There were problems when trying to update this employee'
        render :action => :show
      end
    end
 
    def destroy
      @employee = Employee.find params[:id]

      @employee.destroy
      flash[:notice] = 'Employee has been deleted'
      redirect_to casein_employees_path
    end
  
    private
      
      def employee_params
        params.require(:employee).permit(:name, :description, :email, :phone)
      end

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @brands = Brand.all.order(:name)
    @employees = Employee.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casein/config_helper.rb
module Casein
  module ConfigHelper

    # Name of website or client — used throughout Casein.
    def casein_config_website_name
      'Rafa Distributing'
    end

    # Filename of logo image. Ideally, it should be a transparent PNG around 140x30px
    def casein_config_logo
      'rafa.png'
    end

    # The server hostname where Casein will run
    def casein_config_hostname
      if Rails.env.production?
        'http://rafadistributing.com'
      else
        'http://localhost:3000'
      end
    end

    # The sender address used for email notifications
    def casein_config_email_from_address
      'noreply@rafadistributing.com'
    end

    # The initial page the user is shown after they sign in or click the logo. Probably this should be set to the first tab.
    # Do not point this at casein/index!
    def casein_config_dashboard_url
      url_for :controller => :brands, :action => :index
    end

    # A list of stylesheets to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_stylesheet_includes
      %w[casein/casein casein/custom]
    end

    # A list of JavaScript files to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_javascript_includes
      %w[casein/casein casein/custom]
    end

  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/casein/brands/_form.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<div class="row">
	<div class="col-lg-4 col-md-4">
		<%= casein_text_field f, f.object, :name %>
	</div>
	<div class="col-lg-4 col-md-4">
		<%= casein_file_field f, f.object, @brand, :image %>
	</div>
	<div class="col-lg-4 col-md-4">
		<%= casein_text_field f, f.object, :link %>
	</div>
</div>
<div class="row">
	<div class="col-lg-4 col-md-4 col-md-offset-4">
		<i>Current Image</i>
		<%= image_tag @brand.image.url, class: "img-responsive thumbnail" %>
	</div>
</div>

app/views/casein/brands/_table.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<table class="table table-striped table-hover table-condensed">
	<thead>
		<tr>
			<th><%= casein_sort_link "Name", :name %></th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	
	<% brands.each do |brand| %>
		<tr>
			<td><%= casein_table_cell_link brand.name, casein_brand_path(brand) %></td>
			<td class="delete">
				<%= link_to(casein_show_row_icon("trash"), casein_brand_path(brand), :method => :delete, :data => { :confirm => "Are you sure you want to delete this brand?" }) %>
			</td>
		</tr>
	<% end %>
</table>

app/views/casein/brands/index.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>Brands<%= casein_pagination_details @brands %></h2>

<%= render :partial => 'casein/brands/table', :locals => { :brands => @brands } %>

<div class="text-center">
	<%= will_paginate @brands %>
</div>

<%= content_for :sidebar do %>

	<li><%= link_to "#{casein_show_icon "plus-sign"}Add a new brand".html_safe, new_casein_brand_path %></li>

<% end %>

app/views/casein/brands/new.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>Add a new brand</h2>

<%= form_for @brand, :url => casein_brands_path do |f| %>
	
	<%= render :partial => 'casein/brands/form', :locals => { :f => f } %>
	
	<p class="submits">
		<%= link_to 'Cancel', casein_brands_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Add new brand", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_brands_path %></li>
<% end %>

app/views/casein/brands/show.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>View brand</h2>

<%= form_for @brand, :url => casein_brand_path(@brand) do |f| %>

	<%= render :partial => 'casein/brands/form', :locals => { :f => f } %>

	<p class="submits">
	  	<%= link_to 'Cancel', casein_brands_path, :class => 'btn btn-mini btn-danger' %>
			<%= f.submit "Save changes", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_brands_path %></li>
<% end %>

app/views/casein/employees/_form.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->


<div class="row">
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :name %>
	</div>
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :description %>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :email %>
	</div>
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :phone %>
	</div>
</div>

app/views/casein/employees/_table.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<table class="table table-striped table-hover table-condensed">
	<thead>
		<tr>
			<th><%= casein_sort_link "Name", :name %></th>
			<th><%= casein_sort_link "Description", :description %></th>
			<th><%= casein_sort_link "Email", :email %></th>
			<th><%= casein_sort_link "Phone", :phone %></th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	
	<% employees.each do |employee| %>
		<tr>
			<td><%= casein_table_cell_link employee.name, casein_employee_path(employee) %></td>
			<td><%= casein_table_cell_link employee.description, casein_employee_path(employee) %></td>
			<td><%= casein_table_cell_link employee.email, casein_employee_path(employee) %></td>
			<td><%= casein_table_cell_link employee.phone, casein_employee_path(employee) %></td>
			<td class="delete">
				<%= link_to(casein_show_row_icon("trash"), casein_employee_path(employee), :method => :delete, :data => { :confirm => "Are you sure you want to delete this employee?" }) %>
			</td>
		</tr>
	<% end %>
</table>

app/views/casein/employees/index.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>Employees<%= casein_pagination_details @employees %></h2>

<%= render :partial => 'casein/employees/table', :locals => { :employees => @employees } %>

<div class="text-center">
	<%= will_paginate @employees %>
</div>

<%= content_for :sidebar do %>

	<li><%= link_to "#{casein_show_icon "plus-sign"}Add a new employee".html_safe, new_casein_employee_path %></li>

<% end %>

app/views/casein/employees/new.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>Add a new employee</h2>

<%= form_for @employee, :url => casein_employees_path do |f| %>
	
	<%= render :partial => 'casein/employees/form', :locals => { :f => f } %>
	
	<p class="submits">
		<%= link_to 'Cancel', casein_employees_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Add new employee", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_employees_path %></li>
<% end %>

app/views/casein/employees/show.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>View employee</h2>

<%= form_for @employee, :url => casein_employee_path(@employee) do |f| %>

	<%= render :partial => 'casein/employees/form', :locals => { :f => f } %>
	
	<p class="submits">
	  	<%= link_to 'Cancel', casein_employees_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Save changes", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_employees_path %></li>
<% end %>

app/views/casein/layouts/_tab_navigation.html.erb
<!-- NOTE: the casein:scaffold generator automatically appends new controllers to this file. The SCAFFOLD_INSERT line must NOT be removed -->
<!-- SCAFFOLD_INSERT -->
<li id="tab-employees"><%= link_to "Employees", casein_employees_path %></li>
<li id="tab-brands"><%= link_to "Brands", casein_brands_path %></li>

app/views/casein/layouts/_top_navigation.html.erb
<!-- NOTE: add "hidden-xs hidden-sm" class to li elements you want to be hidden at small browser widths -->
<!-- e.g. <li class="hidden-xs hidden-sm"><%= link_to "Visit site", casein_config_hostname, :target => "_blank" %></li> -->

<li><%= link_to "Visit site", casein_config_hostname, :target => "_blank" %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rafa</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body data-scrollax-parent="true">

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<section class="header center-align">
  <h1>RAFA</h1>
  <h2>distributing</h2>
  <%= image_tag 'mouse.png', class: 'scroller hide-on-med-and-down' %>
</section>

<%= image_tag "hopsketch.png", class: "responsive-img hopsketch" %>
<%= image_tag "hopright.png", class: "responsive-img hopright" %>

<div class="container">
  <div class="row">
    <div class="content-box-1 col m8 s12 offset-m2">
      <p>Rafa Distributing is a boutique craft beer distributor based in Charleston, SC.  We maintain a high-quality portfolio of specialty beer brands, providing the entire state with the most eclectic and unique craft beers available to us. Rafa's mission as a brewer-focused distributor is to assure that our customers are receiving the best selection possible and that beer drinkers throughout South Carolina are drinking just good shit</p>
    </div>
  </div>
<%= image_tag "hopright.png", class: "responsive-img hopright2" %>


  <%= image_tag "hopsketch.png", class: "responsive-img hopsketch2" %>
  <%= image_tag "RAFA_16.png", class: "responsive-img grain" %>

  <div class="row">
    <div class="content-box-4 col l12 m12 s12">
      <h3>CONTACTS</h3>
      <% @employees.each do |e| %>
      <div class="row"> 
        <div class="col m6 s12">
          <p id="names"><%= e.name %></p>
          <p id="titles"><%= e.description %></p>
        </div>
        <div class="col m4 offset-m2 contact-info">
          <p><a href="mailto:<%= e.email %>?Subject=Rafa%20Inquiry" target="_top"><%= e.email %></a><p>
          <p><a href="tel:<%= e.phone %>"><%= e.phone %></a></p>
        </div>
      </div>
      <% end %>
    </div>
</div>

<section class="brands">
  <h1>BRANDS</h1>
  <div class="container">
    <div class="row">
      <% @brands.each do |b| %>
      <div class="col m6 s12">
        <div class="card medium">
          <div class="card-image waves-effect waves-block waves-dark card-overwrite">
            <% unless b.image.blank? %>
              <%= link_to image_tag(b.image), raw(b.link), target: "_blank" %>
            <% end %>
          </div>
          <div class="card-content">
            <p class="card-title grey-text text-darken-4"><%= b.name %></p>
          </div>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</section>